plugins {
    id 'com.android.application'
}
android {
    namespace 'edu.practical.responsive.two'
    compileSdk = 36
    compileSdkMinor = 1
    buildToolsVersion = '36.0.0'
    defaultConfig {
        applicationId 'edu.practical.responsive.two'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
